[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black   = "0x555753"
blue    = "0x729fcf"
cyan    = "0x00f5e9"
green   = "0x8ae234"
magenta = "0xad7fa8"
red     = "0xef2929"
white   = "0xeeeeec"
yellow  = "0xfce94f"

[colors.normal]
black   = "0x2e3436"
blue    = "0x3465a4"
cyan    = "0x0b939b"
green   = "0x4e9a06"
magenta = "0x75507b"
red     = "0xcc0000"
white   = "0xd3d7cf"
yellow  = "0xc4a000"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 13.5
normal      = { family = "SF Mono", style = "Regular"        }
bold        = { family = "SF Mono", style = "Bold"           }
italic      = { family = "SF Mono", style = "Regular Italic" }
bold_italic = { family = "SF Mono", style = "Bold Italic"    }
offset = { x = 1 , y = 0 }

[mouse]
hide_when_typing = true

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/opt/homebrew/bin/zsh"

[window]
dynamic_padding = true
option_as_alt = "Both"
startup_mode = "Maximized"
padding = { x = 4, y = 0 }

[keyboard]
bindings = [
    # disable unwanted default keybindings
    { key = "Q",      mods = "Command", action = "ReceiveChar" },
    { key = "W",      mods = "Command", action = "ReceiveChar" },

    # tmux bindings (https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/)
    { key = "B",        mods = "Command",       chars = "\u001B[24~"            },
    { key = "Key1",     mods = "Command",       chars = "\u001B[24~1"           },
    { key = "Key2",     mods = "Command",       chars = "\u001B[24~2"           },
    { key = "Key3",     mods = "Command",       chars = "\u001B[24~3"           },
    { key = "Key4",     mods = "Command",       chars = "\u001B[24~4"           },
    { key = "Key5",     mods = "Command",       chars = "\u001B[24~5"           },
    { key = "Key6",     mods = "Command",       chars = "\u001B[24~6"           },
    { key = "Key7",     mods = "Command",       chars = "\u001B[24~7"           },
    { key = "Key8",     mods = "Command",       chars = "\u001B[24~8"           },
    { key = "Key9",     mods = "Command",       chars = "\u001B[24~9"           },
    { key = "T",        mods = "Command",       chars = "\u001B[24~c"           },
    { key = "H",        mods = "Command",       chars = "\u001B[24~h"           },
    { key = "J",        mods = "Command",       chars = "\u001B[24~j"           },
    { key = "K",        mods = "Command",       chars = "\u001B[24~k"           },
    { key = "L",        mods = "Command",       chars = "\u001B[24~l"           },
    { key = "{",        mods = "Shift|Command", chars = "\u001B[24~{"           },
    { key = "}",        mods = "Shift|Command", chars = "\u001B[24~}"           },
    { key = "Left",     mods = "Shift|Command", chars = "\u001B[24~\u001B[1;2D" },
    { key = "Right",    mods = "Shift|Command", chars = "\u001B[24~\u001B[1;2C" },
    { key = "Right",    mods = "Command",       chars = "\u001B[24~\u001B[C"    },
    { key = "Left",     mods = "Command",       chars = "\u001B[24~\u001B[D"    },
    { key = "Down",     mods = "Command",       chars = "\u001B[24~\u001B[B"    },
    { key = "Up",       mods = "Command",       chars = "\u001B[24~\u001B[A"    },
    { key = "D",        mods = "Command",       chars = "\u001B[24~v"           },
    { key = "D",        mods = "Shift|Command", chars = "\u001B[24~s"           },
    { key = "LBracket", mods = "Command",       chars = "\u001B[24~["           },
    { key = "F",        mods = "Command",       chars = "\u001B[24~f"           },
    { key = "F",        mods = "Shift|Command", chars = "\u001B[24~F"           },
    { key = "Space",    mods = "Shift|Command", chars = "\u001B[24~ "           }
]
