#!/usr/bin/env bash

listing=$(for rev in $(git rev-list --all); do
    git ls-tree -r "$rev" | grep "$@"
done | awk '
    { if (!($4 in files)) files[$4] = $3 }
    END {
        for (file in files) {
            cmd = "git describe --always " files[file] " | cut -f1 -d':'"
            cmd | getline commit
            close(cmd)
            print file "⌘" files[file] "⌘" commit}
        }
' | sort)

[ -z "$listing" ] && echo "No files found for search '$*'." >&2 && exit 1

printf "file⌘blob⌘commit\n----⌘----⌘------\n%s\n" "$listing" | column -s '⌘' -t
