local function call(fn)
  return ([[<C-\>e luaeval("require('z.commandline').%s()")<CR>]]):format(fn)
end

vim.keymap.set("c", "<C-a>", "<Home>")
vim.keymap.set("c", "<C-b>", "<Left>")
vim.keymap.set("c", "<C-d>", "<Delete>")
vim.keymap.set("c", "<C-e>", "<End>")
vim.keymap.set("c", "<C-f>", "<Right>")
vim.keymap.set("c", "<C-g>", "<C-c>")
vim.keymap.set("c", "<C-n>", "<Down>")
vim.keymap.set("c", "<C-p>", "<Up>")
vim.keymap.set("c", "<C-k>", call("kill_line"))
vim.keymap.set("c", "<M-d>", call("delete_word"))
vim.keymap.set("c", "<M-b>", call("bwd_by_word"))
vim.keymap.set("c", "<M-f>", call("fwd_by_word"))
