require("mono-colors").define("album-256", false, {
  Normal = { ctermfg = 253, ctermbg = 234 },
  Visual = { ctermbg = 232 },
  CursorLine = { ctermbg = 235 },
  CursorLineNr = { ctermfg = 240, ctermbg = 235 },
  LineNr = { ctermfg = 238 },
  StatusLine = { ctermfg = 253, ctermbg = 65 },
  StatusLineNC = { ctermfg = 232, ctermbg = 59 },
  VertSplit = { ctermfg = 232 },
  Comment = { ctermfg = 240 },
  String = { ctermfg = 247 },
  MatchParen = { ctermfg = 215, ctermbg = 236, cterm = { bold = true } },
  Pmenu = { ctermfg = 232, ctermbg = 244 },
  PmenuSbar = { ctermfg = 246, ctermbg = 246 },
  PmenuThumb = { ctermfg = 250, ctermbg = 250 },
  Error = { ctermfg = 197 },
  SpellBad = { ctermfg = 197, cterm = { underline = true } },
  SpellCap = { ctermfg = 215, cterm = { underline = true } },
  Search = { ctermfg = 232, ctermbg = 114 },
  TODO = { ctermfg = 228, cterm = { bold = true, underline = true } },
  DiffAdd = { ctermfg = 120, ctermbg = 29 },
  DiffChange = { ctermfg = 228 },
  DiffText = { ctermfg = 228, ctermbg = 101 },
  DiffDelete = { ctermfg = 197, ctermbg = 88 },
  GitSignsAdd = { ctermfg = 120 },
  GitSignsChange = { ctermfg = 215 },
  GitSignsChangeDelete = { ctermfg = 209 },
  GitSignsDelete = { ctermfg = 197 },
  ErrorMsg = { ctermfg = 231, ctermbg = 197, cterm = { bold = true } },
  WarningMsg = { ctermfg = 231, ctermbg = 173, cterm = { bold = true } },
  BufTabLineActive = { ctermfg = 232, ctermbg = 65 },
  Cursor = { cterm = { reverse = true } },
  TermCursor = { cterm = { reverse = true } },
})
