require("mono-colors").define("dosedit", false, {
  Normal = { ctermfg = 251, ctermbg = 18 },
  Visual = { ctermfg = 16, ctermbg = 251 },
  Cursorline = { ctermbg = 19 },
  CursorLineNr = { ctermbg = 19 },
  StatusLine = { ctermfg = 16, ctermbg = 248 },
  StatusLineNC = { ctermfg = 16, ctermbg = 241 },
  LineNr = { ctermfg = 60 },
  VertSplit = { ctermfg = 248, ctermbg = 16 },
  String = { ctermfg = 103 },
  WarningMsg = { ctermfg = 226 },
  GitSignsAdd = { ctermfg = 46 },
  MatchParen = { ctermfg = 46, cterm = { bold = true } },
  WildMenu = { ctermfg = 248, ctermbg = 16 },
  PmenuSbar = { ctermfg = 244, ctermbg = 240 },
  PmenuThumb = { ctermbg = 231 },
  Error = { ctermfg = 196 },
  SpellBad = { ctermfg = 196, cterm = { underline = true } },
  SpellCap = { ctermfg = 202, cterm = { underline = true } },
  Search = { ctermfg = 231, ctermbg = 127 },
  TODO = { ctermfg = 202, cterm = { bold = true, underline = true } },
  DiffAdd = { ctermfg = 46, ctermbg = 28 },
  DiffChange = { ctermfg = 226 },
  DiffText = { ctermfg = 226, ctermbg = 100 },
  DiffDelete = { ctermfg = 196, ctermbg = 88 },
  GitSignsChangeDelete = { ctermfg = 202 },
})
