#!/usr/bin/env bash

# shamelessly stolen from
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e

# don't make tags for the homebrew repo
(cd .git && pwd) | grep -iq homebrew && exit 0

trap 'rm -f ".git/$$.tags"' EXIT
git ls-files | ctags --tag-relative=yes -L - -f".git/$$.tags"
mv ".git/$$.tags" ".git/tags"
