#! /bin/sh

sxhkd &

bspc config border_width          1
bspc config window_gap            10
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focused_border_color  '#4c7899'
bspc config normal_border_color   '#333333'
bspc config active_border_color   '#333333'

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d 1 2 3 4 5 6
bspc monitor HDMI-2 -d 7 8 9 10 11 12

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --no-fehbg --bg-scale "$XDG_CONFIG_HOME"/sway/darkforest.jpg

lemonbar &
. ~/.config/bspwm/lemonbar.sh
