alias gpg2='gpg2 --homedir "$XDG_CONFIG_HOME/gnupg"'
alias sass='sassc'
alias tmux='tmux -2 -f "$XDG_CONFIG_HOME"/tmux/config'
alias ls='ls -G'
alias ll='ls -lhG'
alias vim='nvim'
alias less='less -IR'
alias irssi='irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_CONFIG_HOME"/irssi'
alias startx='startx "$XDG_CONFIG_HOME"/x11/xinitrc'
alias xmllint='xmllint --format'
alias nb='newsboat'
alias sqlite3='sqlite3 -init "$XDG_CONFIG_HOME"/sqlite3/sqliterc'
alias id3v2='mid3v2'
alias svn='svn --config-dir "$XDG_CONFIG_HOME"/subversion'
alias b='brew'
