alias gpg2='gpg2 --homedir "$XDG_CONFIG_HOME/gnupg"'
alias sass='sassc'
alias tmux='tmux -2 -f "$XDG_CONFIG_HOME"/tmux/config'
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias vim='nvim'
alias less='less -R'
alias pacman='pacman --color=always'
alias irssi='irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_CONFIG_HOME"/irssi'
alias sway='sway-run.zsh'
alias startx='startx "$XDG_CONFIG_HOME"/x11/xinitrc'
alias xmllint='xmllint --format'
alias hog='du --max-depth=1 | sort -n'
alias nb='newsbeuter'
alias sqlite3='sqlite3 -init "$XDG_CONFIG_HOME"/sqlite3/sqliterc'
alias id3v2='mid3v2'
