export PATH=$HOME/.cargo/bin:/usr/local/bin:/opt/homebrew/bin:/usr/local/opt/sqlite/bin:$PATH
export XDG_RUNTIME_DIR=$TMPDIR
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/Library/Caches
export XDG_DATA_HOME="$HOME"/Library
export EDITOR=nvim
export INPUTRC="$XDG_CONFIG_HOME"/inputrc
export PAGER='less -iXR'
export LESSHISTFILE=-
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node/history
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/startup.py
export VIRTUAL_ENV_DISABLE_PROMPT=1
export VISUAL=nvim
export LSCOLORS=ExGxFxFxCx
export HOMEBREW_NO_ANALYTICS=1
export REPORTTIME=5
